# Generated by Django 4.2.7 on 2023-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_task_issubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquiz',
            name='correctAns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='textAns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
