# Generated by Django 4.2.7 on 2023-11-24 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_answerquiz_correctans_answerquiz_textans'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquiz',
            name='taskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.task'),
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
