# Generated by Django 4.2.7 on 2023-11-25 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_answerquiz_taskid_answerquiz_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(blank=True, null=True)),
                ('mark', models.FloatField()),
                ('sClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.vclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workToDo', models.ManyToManyField(blank=True, related_name='student', to='quiz.work')),
            ],
        ),
    ]
