# Generated by Django 4.2.7 on 2023-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
