# Generated by Django 4.2.7 on 2023-11-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0010_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='toUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.work'),
        ),
    ]
