# Generated by Django 4.2.7 on 2023-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_answerquiz_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uAnswer',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answerquiz',
            name='uAnswer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
