# Generated by Django 4.2.7 on 2023-11-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_task_touser_task_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='rightAnswCount',
        ),
        migrations.AddField(
            model_name='task',
            name='rightAnsw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='uAnswer',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answerquiz',
            name='taskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.task'),
        ),
        migrations.AlterField(
            model_name='answerquiz',
            name='uAnswer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='toUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.work'),
        ),
    ]
