# Generated by Django 4.2.7 on 2023-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_task_rightanswcount_task_rightansw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='numbOfTasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
