# Generated by Django 4.2.7 on 2023-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
