# Generated by Django 4.2.7 on 2023-11-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0004_task_variant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='task',
            name='variants',
            field=models.ManyToManyField(related_name='tasks', to='ariphm.variant'),
        ),
    ]
