# Generated by Django 4.2.7 on 2023-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0005_remove_task_variant_id_task_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('answer', models.IntegerField(default=0)),
                ('succ', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variants', models.ManyToManyField(related_name='taskLists', to='ariphm.variant')),
            ],
        ),
    ]
