# Generated by Django 4.2.7 on 2023-11-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0006_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='variants',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='varNumber',
            field=models.IntegerField(default=0),
        ),
    ]
