# Generated by Django 4.2.7 on 2023-11-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0009_answerquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='taskId',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='variants',
        ),
        migrations.DeleteModel(
            name='AnswerQuiz',
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='taskList',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
